spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bugtracker
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/bugtracker
    change-log: classpath:db/changelog/db.changelog-master.xml
  application:
    name: bug-tracker-api
  h2:
    console:
      enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  logging:
    config: classpath:logback-spring.xml
server:
  port: 8080
configs:
  tokenConfigs:
    secretKey: secretKey
    expiredIn: 3600000

---

spring:
  profiles: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/bugtracker
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/bugtracker
    change-log: classpath:db/changelog/db.changelog-master.xml
  application:
    name: bug-tracker-auth-server
  h2:
    console:
      enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  logging:
    config: classpath:logback-spring.xml
server:
  port: 8081
configs:
  tokenConfigs:
    secretKey: secretKey
    expiredIn: 3600000  