spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bugtracker
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/bugtracker
    change-log: classpath:db/changelog/db.changelog-master.xml
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  path: /logs/
  file: app.log
  level:
    root: INFO
    org:
      springframework:
    security: DEBUG
server:
  port: 8080
  servlet:
    context-path: /api
